// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Chronas.ChronasTimeTracker.OnSceneViewGUI(UnityEditor.SceneView)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Chronas.ChronasTimeTracker.DeleteTimeCard(LivingDevAgent.Editor.Chronas.ChronasTimeTracker.ChronasTimeCard)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Chronas.ChronasTimeTracker.EnsureStaticTimerInitialized")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Chronas.ChronasTimeTracker.GetCurrentSessionTime~System.Double")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Chronas.ChronasTimeTracker.LoadTimeCards")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Chronas.ChronasTimeTracker.SaveCurrentSession")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Chronas.ChronasTimeTracker.StopTracking")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.EditorModule.AddImageAndInsertAtCursor")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.EditorModule.EnsureImagesDirectory~System.String")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.EditorModule.HandleCursorTracking")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.EditorModule.InsertImageMarkdownAtCursor(System.String)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.EditorModule.ParseBasicMetadata(System.String)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.EditorModule.ResolveActiveFolder~System.String")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.FormModule.BuildMarkdown~System.String")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.FormModule.ClockOut")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.FormModule.PauseWithNote")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.FormModule.ResolveActiveFolder~System.String")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.FormModule.TryCreateTLDL")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.FormModule.WarnOverwriteRawIfDirty~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.NavigatorModule.AddTextureToCache(System.String,UnityEngine.Texture2D)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.NavigatorModule.AppendDirectorySeparatorChar(System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.NavigatorModule.DrawDirectoryNode(System.String,System.Int32,System.String)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.NavigatorModule.GetRelativePath(System.String,System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.NavigatorModule.OpenContainingFolderOfFile(System.String)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.NavigatorModule.OpenInFileBrowser(System.String)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.NavigatorModule.ParseBasicMetadata(System.String)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.NavigatorModule.ResolveActiveFolder~System.String")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.PreviewModule.ApplyInlineFormatting(System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.ScribeModuleBase.InitializeSharedStyles")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.TaskMasterModule.ClockOut")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.TaskMasterModule.LoadTimeCards")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.TaskMasterModule.OnSceneGUI(UnityEditor.SceneView)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.TaskMasterModule.SaveCurrentSession")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.TemplateModule.EnsureIssuesReadme(System.String)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.TemplateModule.EnsureTemplatesLoaded")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.Modules.TemplateModule.PostWriteImport(System.String)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.TaskMaster.TaskMasterWindow.DrawSidebar")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.TaskMaster.TaskMasterWindow.DrawTopToolbar")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.TLDLScribeWindow.CreateNavBackgroundTexture~UnityEngine.Texture2D")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.TLDLScribeWindow.InitializeStyles")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:LivingDevAgent.Editor.TLDLScribeWindow.OnGUI")]
